### PR TITLE
make PiShrink work on/from SD

### PR DESCRIPTION
**Pull request by cskiraly**
I have implemented some changes to make PiShrink work directly from the SD device (e.g. /dev/mmcblk0).
It support 3 modes from SD:
- copy from SD to image file and shrink
- shrink directly on SD
- shrink directly on SD and copy to image file.
This last, one, using the new -i flag, is useful when one works with high capacity SD cards.

### CODE REVIEW

**Comment by Drewsif** [comment]
It looks like it needs some tweeting to get it working since using loop back devices aren't needed on block devices. I merged it into the dev branch and will do a bit of work on it.

**Comment by cskiraly** [comment]
Loop is clearly an overhead, but working as is for me. Thanks, and feel free to make it more streamlined.

**Comment by agsdot** [comment]
@cskiraly and @Drewsif , can you include more instructions on how to 

- shrink directly on SD
- shrink directly on SD and copy to image file.

In the README.md file?

Thanks!

**Comment by Drewsif** [comment]
Once I have more time to work on it there will be instructions on it in the readme

**Comment by agsdot** [comment]
@Drewsif, thanks for the update.  Looking forward to seeing the updates on the readme.

**Pull request merged**
