### PR TITLE
reverted to using raspi-config to be used for automatic image resizing

### PR DESCRIPTION
**Pull request by shatteredsword**
while not having to rely on the raspi-config tool does make the pishrink utility more portable, the raspi-config tool is already properly maintained. rather than being forced to maintain the autosizing utility in this script (which has already been broken for several months due to a linux kernal change), it just makes more sense to not have to rewrite properly maintained code.

### CODE REVIEW

**Comment by russau** [comment]
FYI this addressed the issue I reported with newer versions of Raspbian #18

**Comment by shatteredsword** [comment]
@russau good to hear. I added this pull request because the auto-expand feature stopped working a few months ago when there was a linux kernal update that i'm pretty sure broke it.

**Comment by Drewsif** [comment]
Thanks for the fix! I still want to keep the auto-expand working on distros that don't have raspi-config. But That will be added to the todo list!

**Comment by shatteredsword** [comment]
ahh, gotcha. i wasn't aware that the script even worked on other distros.

**Pull request merged**
