### PR TITLE
Offer filesystem repair options

### PR DESCRIPTION
**Pull request by framps**
This PR is a result of a discussion in a [German Raspberry forum](https://forum-raspberrypi.de/forum/thread/39858-sicherung-der-sd-karte/?pageNo=1) where a user of pishrink had a corrupted image he tried to shrink with pishrink but failed.

New option -r executes some fsck on the image to repair the image filesystem. Option -p executes paranoia fsck cycles.

### CODE REVIEW

**Comment by Drewsif** [comment]
I looked over this real quick and I'm a bit confused on `-r` vs `-p`. Both say they require `newimagefile.img` to be specified. Was the idea that this would not be the case with `-r`?

My initial thought is that `-p` could be removed and a documentation warning could be added to `-r` but I'm curious your thoughts on it.

**Comment by kapitainsky** [comment]
tried this and it does not work (it works with original pishrink script)

when I run:

```
sudo pishrink.sh -d -r -p img.img img-shrunken.img
```
it fails with the following error:

```
pishrink.sh: Creating log file /tmp/pishrink.log...
pishrink.sh v0.1.1
pishrink.sh: Copying img.img to img-shrunken.img......
pishrink.sh: Gatherin data...
Creating new /etc/rc.local
resize2fs 1.43.4 (31-Jan-2017)
pishrink.sh: Shrinking filesystem...
resize2fs 1.43.4 (31-Jan-2017)
Please run 'e2fsck -f /dev/loop0' first.

pishrink.sh: ERROR occured in line 310: resize2fs failed
mount: /dev/loop0: can't read superblock
mv: cannot stat '/tmp/tmp.7fjRhpzuEA/etc/rc.local.bak': No such file or directory
umount: /tmp/tmp.7fjRhpzuEA: not mounted
losetup: /dev/loop0: detach failed: No such device or address
```

**Comment by kapitainsky** [comment]
line

```
if [[ repair == true ]]; then
```

does not do what is intended

i suggest to test  and use https://www.shellcheck.net before

**Comment by framps** [comment]
> I looked over this real quick and I'm a bit confused on `-r` vs `-p`. Both say they require `newimagefile.img` to be specified. Was the idea that this would not be the case with `-r`?
-r repairs the filesystem. -p is the paranoia mode of -r and some additional e2fsck calls are executed. We also may drop -r and have -p only.

**Comment by framps** [comment]
> if [[ repair == true ]]; then
> ```
> 
> does not do what is intended

Fixed right now. Thank you very much to report this typo

**Comment by Drewsif** [comment]
I've thought about it and I like the idea of having repair be the default, there are too many reports from people who just needed to run a repair.

The only question I have is about the retries. Does running the same command 3 times ever have an effect? I assume if the filesystem is too messed up to repair that it wouldn't work the first time I assume it wouldn't do much to try again, but I have nothing to back up my assumption with 😋

**Comment by framps** [comment]
> Does running the same command 3 times ever have an effect? 
The sequence of commands executed in the paranoia mode was heavily discussed in the linked German forum thread. Every time different options are used. User RTFM is a subject matter expert on this issue and I actually followed his advises and wrote the code. 
Frankly this option is not heavily tested because of missing different flavors of corrupted images and the complexity to create corrupted test images. So I consider the `-p` option as experimental whereas I consider `-r` as a normal option. But this option will increase the execution time and will double the required disk space because the repairs are done on a copy of the original image. That's why i decided to keep option `-r` optional. But feel free to change the logic :wink:

**Pull request closed without merging**
