### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by lurch**
Various tweaks and tidyups. Apologies for squeezing so many commits into a single PR, but these are all fairly small changes, which are hopefully non-controversial! :wink: 

Happy to break this up into separate PRs if that's what you'd prefer.

### CODE REVIEW

**Comment by Drewsif** [comment]
Having it all in one is fine with me, I just want to give it a quick test on my end but it looks good!

**Comment by lurch** [comment]
Have now rebased to get rid of the merge conflict :)

**Comment by Drewsif** [comment]
Tested it and it worked fine for me. Thanks for taking the time to do this, I really appreciate your effort! 😄

**Comment by framps** [comment]
Very valuable PR 👍

**Pull request merged**
