### PR TITLE
adding macOS support via Docker

### PR DESCRIPTION
**Pull request by a2f0**
This will allow you to run PiShrink on macOS with a Docker engine installed.  I think this will also work on Linux but I haven't tested it.

### CODE REVIEW

**Comment by revolunet** [comment]
awesome addition thanks 👍

**Comment by miathedev** [comment]
It works on Linux :+1:

**Comment by pablobuenaposada** [comment]
it works, please merge it

**Comment by deepeeess** [comment]
@pablobuenaposada commits have been squashed as requested.

**Comment by deepeeess** [comment]
@miathedev on MacOS I get a bunch of errors when I invoke docker-compose without `privileged: true` in the docker-compose.yml.  I did remove `privileged: true` and re-add it and verify these go away.

```
WARNING: Image for service pishrink was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
losetup: /pishrink/universal.img: failed to set up loop device: Operation not permitted
Usage: tune2fs [-c max_mounts_count] [-e errors_behavior] [-f] [-g group]
	[-i interval[d|m|w]] [-j] [-J journal_options] [-l]
	[-m reserved_blocks_percent] [-o [^]mount_options[,...]]
	[-r reserved_blocks_count] [-u user] [-C mount_count]
	[-L volume_label] [-M last_mounted_dir]
	[-O [^]feature[,...]] [-Q quota_options]
	[-E extended-option[,...]] [-T last_check_time] [-U UUID]
	[-I new_inode_size] [-z undo_file] device
Usage: tune2fs [-c max_mounts_count] [-e errors_behavior] [-f] [-g group]
	[-i interval[d|m|w]] [-j] [-J journal_options] [-l]
	[-m reserved_blocks_percent] [-o [^]mount_options[,...]]
	[-r reserved_blocks_count] [-u user] [-C mount_count]
	[-L volume_label] [-M last_mounted_dir]
	[-O [^]feature[,...]] [-Q quota_options]
	[-E extended-option[,...]] [-T last_check_time] [-U UUID]
	[-I new_inode_size] [-z undo_file] device
mount: /tmp/tmp.92SPHlr0rf: can't find in /etc/fstab.
md5sum: /tmp/tmp.92SPHlr0rf/etc/rc.local: No such file or directory
/pishrink/pishrink.sh: line 63: [: !=: unary operator expected
umount: /tmp/tmp.92SPHlr0rf: must be superuser to unmount.
Usage: e2fsck [-panyrcdfktvDFV] [-b superblock] [-B blocksize]
		[-l|-L bad_blocks_file] [-C fd] [-j external_journal]
		[-E extended-options] [-z undo_file] device

Emergency help:
 -p                   Automatic repair (no questions)
 -n                   Make no changes to the filesystem
 -y                   Assume "yes" to all questions
 -c                   Check for bad blocks and add them to the badblock list
 -f                   Force checking even if filesystem is marked clean
 -v                   Be verbose
 -b superblock        Use alternative superblock
 -B blocksize         Force blocksize when looking for superblock
 -j external_journal  Set location of the external journal
 -l bad_blocks_file   Add to badblocks list
 -L bad_blocks_file   Set badblocks list
 -z undo_file         Create an undo file
resize2fs 1.44.1 (24-Mar-2018)
Usage: resize2fs [-d debug_flags] [-f] [-F] [-M] [-P] [-p] device [-b|-s|new_size] [-S RAID-stride] [-z undo_file]
```

**Comment by pablobuenaposada** [comment]
it's a shame nothing gets merged 😢 
@deepeeess thanks anyway

**Comment by deepeeess** [comment]
All good I still have hope @pablobuenaposada.  No merge conflicts yet 😜

**Comment by pablobuenaposada** [comment]
> All good I still have hope @pablobuenaposada. No merge conflicts yet 😜

probably a rebase would help?

**Comment by deepeeess** [comment]
I dunno, I'm not a git expert but I've kind of stopped using rebase because it messes with the history.  If rebasing would help get this merged I'm wiling to do it.

**Comment by pablobuenaposada** [comment]
You can put your commit on top with `git rebase -i` for example, shouldn't be any problem.
The thing is that there are quite some commits after this one and would be nice to test it with everything up to date.

**Comment by Drewsif** [comment]
You don't need to rebase it. I just have not had time to get to this particular issue and test it. It's next on my list for the project though!

**Comment by pablobuenaposada** [comment]
I think not rebasing is a silly move, you would test it with old code, would work, and you will merge it giving the chance that the new commits mess up the dockerization and having a broken master until someone tells you about 🤷‍♂

**Comment by Drewsif** [comment]
I would merge in master before I start testing, don't worry about that ;)

**Comment by pablobuenaposada** [comment]
well, here you have the first conflict, then can we rebase now?

**Comment by deepeeess** [comment]
@pablobuenaposada I resolved the merge conflict.

**Comment by mgomesborges** [comment]
Hey @deepeeess @miathedev @pablobuenaposada you can use [PiShrink dockerized](https://github.com/mgomesborges/pishrink-docker) | [Docker Hub PiShrink](https://hub.docker.com/r/mgomesborges/pishrink):

## macOS Setup

1. [Install Docker Desktop on Mac](https://docs.docker.com/docker-for-mac/install/)

2. Make a copy of a Raspberry Pi SD card that you want to shrink ([see instructions here](https://github.com/mgomesborges/raspberry-pi/blob/master/setup/clone-sd-card.md)).

3. Using the Terminal, access the directory containing the Raspberry Pi image:

```bash
cd ~/Directory-with-RPi-image
```

4. Run PiShrink dockerized:

```bash
docker run --privileged=true --rm \
    --volume $(pwd):/workdir \
    mgomesborges/pishrink \
    pishrink -pZv IMAGE_NAME.img NEW-IMAGE_NAME.img
```

**Comment by miathedev** [comment]
Didnt expect that this issue still exist after this time! @Drewsif what speaks against a merge?

**Comment by pablobuenaposada** [comment]
I don't get it honestly, other people are starting to create their own repos with this project dockerized because this is getting postponed again and again.

**Comment by Axel-Jacobsen** [comment]
ping @Drewsif! Is it possible to merge this?

**Comment by Drewsif** [comment]
Closing. Added docker in [1fe1137](https://github.com/Drewsif/PiShrink/commit/1fe1137ddd6db2c11847697902bdeb213cca1479). Sorry for the delays

**Comment by Axel-Jacobsen** [comment]
Woo!

**Pull request closed without merging**
